// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: inheritence.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtobufNet.Grpc.Test.Integration.Protoc {

  /// <summary>Holder for reflection information generated from inheritence.proto</summary>
  public static partial class InheritenceReflection {

    #region Descriptor
    /// <summary>File descriptor for inheritence.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InheritenceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFpbmhlcml0ZW5jZS5wcm90bxIpcHJvdG9idWZfbmV0LkdycGMuVGVzdC5J",
            "bnRlZ3JhdGlvbi5Qcm90b2MiyQIKBEJhc2USDgoGU3RyaW5nGAEgASgJEl8K",
            "EFN0cmluZ0RpY3Rpb25hcnkYAiADKAsyRS5wcm90b2J1Zl9uZXQuR3JwYy5U",
            "ZXN0LkludGVncmF0aW9uLlByb3RvYy5CYXNlLlN0cmluZ0RpY3Rpb25hcnlF",
            "bnRyeRI9CgNTdWIYCiABKAsyLi5wcm90b2J1Zl9uZXQuR3JwYy5UZXN0Lklu",
            "dGVncmF0aW9uLlByb3RvYy5TdWJIABJNCgtHZW5lcmljQmFzZRgLIAEoCzI2",
            "LnByb3RvYnVmX25ldC5HcnBjLlRlc3QuSW50ZWdyYXRpb24uUHJvdG9jLkdl",
            "bmVyaWNCYXNlSAAaNwoVU3RyaW5nRGljdGlvbmFyeUVudHJ5EgsKA2tleRgB",
            "IAEoCRINCgV2YWx1ZRgCIAEoCToCOAFCCQoHc3VidHlwZSJLCgtHZW5lcmlj",
            "QmFzZRI8CgZSZXN1bHQYASABKAsyLC5wcm90b2J1Zl9uZXQuR3JwYy5UZXN0",
            "LkludGVncmF0aW9uLlByb3RvYy5UIqsBChBHZW5lcmljQmFzZV9Qb2NvEj8K",
            "BlJlc3VsdBgBIAEoCzIvLnByb3RvYnVmX25ldC5HcnBjLlRlc3QuSW50ZWdy",
            "YXRpb24uUHJvdG9jLlBvY28SSwoKU3ViR2VuZXJpYxgUIAEoCzI1LnByb3Rv",
            "YnVmX25ldC5HcnBjLlRlc3QuSW50ZWdyYXRpb24uUHJvdG9jLlN1YkdlbmVy",
            "aWNIAEIJCgdzdWJ0eXBlIhUKBFBvY28SDQoFU2hvcnQYASABKAUiEwoDU3Vi",
            "EgwKBExvbmcYASABKAMiGQoKU3ViR2VuZXJpYxILCgNJbnQYASABKAUiAwoB",
            "VGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNet.Grpc.Test.Integration.Protoc.Base), global::ProtobufNet.Grpc.Test.Integration.Protoc.Base.Parser, new[]{ "String", "StringDictionary", "Sub", "GenericBase" }, new[]{ "Subtype" }, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNet.Grpc.Test.Integration.Protoc.GenericBase), global::ProtobufNet.Grpc.Test.Integration.Protoc.GenericBase.Parser, new[]{ "Result" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNet.Grpc.Test.Integration.Protoc.GenericBase_Poco), global::ProtobufNet.Grpc.Test.Integration.Protoc.GenericBase_Poco.Parser, new[]{ "Result", "SubGeneric" }, new[]{ "Subtype" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNet.Grpc.Test.Integration.Protoc.Poco), global::ProtobufNet.Grpc.Test.Integration.Protoc.Poco.Parser, new[]{ "Short" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNet.Grpc.Test.Integration.Protoc.Sub), global::ProtobufNet.Grpc.Test.Integration.Protoc.Sub.Parser, new[]{ "Long" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNet.Grpc.Test.Integration.Protoc.SubGeneric), global::ProtobufNet.Grpc.Test.Integration.Protoc.SubGeneric.Parser, new[]{ "Int" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNet.Grpc.Test.Integration.Protoc.T), global::ProtobufNet.Grpc.Test.Integration.Protoc.T.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Base : pb::IMessage<Base> {
    private static readonly pb::MessageParser<Base> _parser = new pb::MessageParser<Base>(() => new Base());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Base> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNet.Grpc.Test.Integration.Protoc.InheritenceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Base() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Base(Base other) : this() {
      string_ = other.string_;
      stringDictionary_ = other.stringDictionary_.Clone();
      switch (other.SubtypeCase) {
        case SubtypeOneofCase.Sub:
          Sub = other.Sub.Clone();
          break;
        case SubtypeOneofCase.GenericBase:
          GenericBase = other.GenericBase.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Base Clone() {
      return new Base(this);
    }

    /// <summary>Field number for the "String" field.</summary>
    public const int StringFieldNumber = 1;
    private string string_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string String {
      get { return string_; }
      set {
        string_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "StringDictionary" field.</summary>
    public const int StringDictionaryFieldNumber = 2;
    private static readonly pbc::MapField<string, string>.Codec _map_stringDictionary_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 18);
    private readonly pbc::MapField<string, string> stringDictionary_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> StringDictionary {
      get { return stringDictionary_; }
    }

    /// <summary>Field number for the "Sub" field.</summary>
    public const int SubFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtobufNet.Grpc.Test.Integration.Protoc.Sub Sub {
      get { return subtypeCase_ == SubtypeOneofCase.Sub ? (global::ProtobufNet.Grpc.Test.Integration.Protoc.Sub) subtype_ : null; }
      set {
        subtype_ = value;
        subtypeCase_ = value == null ? SubtypeOneofCase.None : SubtypeOneofCase.Sub;
      }
    }

    /// <summary>Field number for the "GenericBase" field.</summary>
    public const int GenericBaseFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtobufNet.Grpc.Test.Integration.Protoc.GenericBase GenericBase {
      get { return subtypeCase_ == SubtypeOneofCase.GenericBase ? (global::ProtobufNet.Grpc.Test.Integration.Protoc.GenericBase) subtype_ : null; }
      set {
        subtype_ = value;
        subtypeCase_ = value == null ? SubtypeOneofCase.None : SubtypeOneofCase.GenericBase;
      }
    }

    private object subtype_;
    /// <summary>Enum of possible cases for the "subtype" oneof.</summary>
    public enum SubtypeOneofCase {
      None = 0,
      Sub = 10,
      GenericBase = 11,
    }
    private SubtypeOneofCase subtypeCase_ = SubtypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubtypeOneofCase SubtypeCase {
      get { return subtypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSubtype() {
      subtypeCase_ = SubtypeOneofCase.None;
      subtype_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Base);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Base other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (String != other.String) return false;
      if (!StringDictionary.Equals(other.StringDictionary)) return false;
      if (!object.Equals(Sub, other.Sub)) return false;
      if (!object.Equals(GenericBase, other.GenericBase)) return false;
      if (SubtypeCase != other.SubtypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (String.Length != 0) hash ^= String.GetHashCode();
      hash ^= StringDictionary.GetHashCode();
      if (subtypeCase_ == SubtypeOneofCase.Sub) hash ^= Sub.GetHashCode();
      if (subtypeCase_ == SubtypeOneofCase.GenericBase) hash ^= GenericBase.GetHashCode();
      hash ^= (int) subtypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (String.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(String);
      }
      stringDictionary_.WriteTo(output, _map_stringDictionary_codec);
      if (subtypeCase_ == SubtypeOneofCase.Sub) {
        output.WriteRawTag(82);
        output.WriteMessage(Sub);
      }
      if (subtypeCase_ == SubtypeOneofCase.GenericBase) {
        output.WriteRawTag(90);
        output.WriteMessage(GenericBase);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (String.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(String);
      }
      size += stringDictionary_.CalculateSize(_map_stringDictionary_codec);
      if (subtypeCase_ == SubtypeOneofCase.Sub) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sub);
      }
      if (subtypeCase_ == SubtypeOneofCase.GenericBase) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GenericBase);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Base other) {
      if (other == null) {
        return;
      }
      if (other.String.Length != 0) {
        String = other.String;
      }
      stringDictionary_.Add(other.stringDictionary_);
      switch (other.SubtypeCase) {
        case SubtypeOneofCase.Sub:
          if (Sub == null) {
            Sub = new global::ProtobufNet.Grpc.Test.Integration.Protoc.Sub();
          }
          Sub.MergeFrom(other.Sub);
          break;
        case SubtypeOneofCase.GenericBase:
          if (GenericBase == null) {
            GenericBase = new global::ProtobufNet.Grpc.Test.Integration.Protoc.GenericBase();
          }
          GenericBase.MergeFrom(other.GenericBase);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            String = input.ReadString();
            break;
          }
          case 18: {
            stringDictionary_.AddEntriesFrom(input, _map_stringDictionary_codec);
            break;
          }
          case 82: {
            global::ProtobufNet.Grpc.Test.Integration.Protoc.Sub subBuilder = new global::ProtobufNet.Grpc.Test.Integration.Protoc.Sub();
            if (subtypeCase_ == SubtypeOneofCase.Sub) {
              subBuilder.MergeFrom(Sub);
            }
            input.ReadMessage(subBuilder);
            Sub = subBuilder;
            break;
          }
          case 90: {
            global::ProtobufNet.Grpc.Test.Integration.Protoc.GenericBase subBuilder = new global::ProtobufNet.Grpc.Test.Integration.Protoc.GenericBase();
            if (subtypeCase_ == SubtypeOneofCase.GenericBase) {
              subBuilder.MergeFrom(GenericBase);
            }
            input.ReadMessage(subBuilder);
            GenericBase = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class GenericBase : pb::IMessage<GenericBase> {
    private static readonly pb::MessageParser<GenericBase> _parser = new pb::MessageParser<GenericBase>(() => new GenericBase());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GenericBase> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNet.Grpc.Test.Integration.Protoc.InheritenceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenericBase() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenericBase(GenericBase other) : this() {
      result_ = other.result_ != null ? other.result_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenericBase Clone() {
      return new GenericBase(this);
    }

    /// <summary>Field number for the "Result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::ProtobufNet.Grpc.Test.Integration.Protoc.T result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtobufNet.Grpc.Test.Integration.Protoc.T Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GenericBase);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GenericBase other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Result, other.Result)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (result_ != null) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GenericBase other) {
      if (other == null) {
        return;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::ProtobufNet.Grpc.Test.Integration.Protoc.T();
        }
        Result.MergeFrom(other.Result);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::ProtobufNet.Grpc.Test.Integration.Protoc.T();
            }
            input.ReadMessage(Result);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GenericBase_Poco : pb::IMessage<GenericBase_Poco> {
    private static readonly pb::MessageParser<GenericBase_Poco> _parser = new pb::MessageParser<GenericBase_Poco>(() => new GenericBase_Poco());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GenericBase_Poco> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNet.Grpc.Test.Integration.Protoc.InheritenceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenericBase_Poco() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenericBase_Poco(GenericBase_Poco other) : this() {
      result_ = other.result_ != null ? other.result_.Clone() : null;
      switch (other.SubtypeCase) {
        case SubtypeOneofCase.SubGeneric:
          SubGeneric = other.SubGeneric.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GenericBase_Poco Clone() {
      return new GenericBase_Poco(this);
    }

    /// <summary>Field number for the "Result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::ProtobufNet.Grpc.Test.Integration.Protoc.Poco result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtobufNet.Grpc.Test.Integration.Protoc.Poco Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "SubGeneric" field.</summary>
    public const int SubGenericFieldNumber = 20;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ProtobufNet.Grpc.Test.Integration.Protoc.SubGeneric SubGeneric {
      get { return subtypeCase_ == SubtypeOneofCase.SubGeneric ? (global::ProtobufNet.Grpc.Test.Integration.Protoc.SubGeneric) subtype_ : null; }
      set {
        subtype_ = value;
        subtypeCase_ = value == null ? SubtypeOneofCase.None : SubtypeOneofCase.SubGeneric;
      }
    }

    private object subtype_;
    /// <summary>Enum of possible cases for the "subtype" oneof.</summary>
    public enum SubtypeOneofCase {
      None = 0,
      SubGeneric = 20,
    }
    private SubtypeOneofCase subtypeCase_ = SubtypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubtypeOneofCase SubtypeCase {
      get { return subtypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSubtype() {
      subtypeCase_ = SubtypeOneofCase.None;
      subtype_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GenericBase_Poco);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GenericBase_Poco other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Result, other.Result)) return false;
      if (!object.Equals(SubGeneric, other.SubGeneric)) return false;
      if (SubtypeCase != other.SubtypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (result_ != null) hash ^= Result.GetHashCode();
      if (subtypeCase_ == SubtypeOneofCase.SubGeneric) hash ^= SubGeneric.GetHashCode();
      hash ^= (int) subtypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (result_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Result);
      }
      if (subtypeCase_ == SubtypeOneofCase.SubGeneric) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(SubGeneric);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      if (subtypeCase_ == SubtypeOneofCase.SubGeneric) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(SubGeneric);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GenericBase_Poco other) {
      if (other == null) {
        return;
      }
      if (other.result_ != null) {
        if (result_ == null) {
          Result = new global::ProtobufNet.Grpc.Test.Integration.Protoc.Poco();
        }
        Result.MergeFrom(other.Result);
      }
      switch (other.SubtypeCase) {
        case SubtypeOneofCase.SubGeneric:
          if (SubGeneric == null) {
            SubGeneric = new global::ProtobufNet.Grpc.Test.Integration.Protoc.SubGeneric();
          }
          SubGeneric.MergeFrom(other.SubGeneric);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (result_ == null) {
              Result = new global::ProtobufNet.Grpc.Test.Integration.Protoc.Poco();
            }
            input.ReadMessage(Result);
            break;
          }
          case 162: {
            global::ProtobufNet.Grpc.Test.Integration.Protoc.SubGeneric subBuilder = new global::ProtobufNet.Grpc.Test.Integration.Protoc.SubGeneric();
            if (subtypeCase_ == SubtypeOneofCase.SubGeneric) {
              subBuilder.MergeFrom(SubGeneric);
            }
            input.ReadMessage(subBuilder);
            SubGeneric = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class Poco : pb::IMessage<Poco> {
    private static readonly pb::MessageParser<Poco> _parser = new pb::MessageParser<Poco>(() => new Poco());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Poco> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNet.Grpc.Test.Integration.Protoc.InheritenceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Poco() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Poco(Poco other) : this() {
      short_ = other.short_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Poco Clone() {
      return new Poco(this);
    }

    /// <summary>Field number for the "Short" field.</summary>
    public const int ShortFieldNumber = 1;
    private int short_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Short {
      get { return short_; }
      set {
        short_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Poco);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Poco other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Short != other.Short) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Short != 0) hash ^= Short.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Short != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Short);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Short != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Short);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Poco other) {
      if (other == null) {
        return;
      }
      if (other.Short != 0) {
        Short = other.Short;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Short = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Sub : pb::IMessage<Sub> {
    private static readonly pb::MessageParser<Sub> _parser = new pb::MessageParser<Sub>(() => new Sub());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Sub> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNet.Grpc.Test.Integration.Protoc.InheritenceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Sub() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Sub(Sub other) : this() {
      long_ = other.long_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Sub Clone() {
      return new Sub(this);
    }

    /// <summary>Field number for the "Long" field.</summary>
    public const int LongFieldNumber = 1;
    private long long_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Long {
      get { return long_; }
      set {
        long_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Sub);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Sub other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Long != other.Long) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Long != 0L) hash ^= Long.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Long != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Long);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Long != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Long);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Sub other) {
      if (other == null) {
        return;
      }
      if (other.Long != 0L) {
        Long = other.Long;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Long = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SubGeneric : pb::IMessage<SubGeneric> {
    private static readonly pb::MessageParser<SubGeneric> _parser = new pb::MessageParser<SubGeneric>(() => new SubGeneric());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SubGeneric> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNet.Grpc.Test.Integration.Protoc.InheritenceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubGeneric() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubGeneric(SubGeneric other) : this() {
      int_ = other.int_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubGeneric Clone() {
      return new SubGeneric(this);
    }

    /// <summary>Field number for the "Int" field.</summary>
    public const int IntFieldNumber = 1;
    private int int_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Int {
      get { return int_; }
      set {
        int_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SubGeneric);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SubGeneric other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Int != other.Int) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Int != 0) hash ^= Int.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Int != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Int);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Int != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Int);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SubGeneric other) {
      if (other == null) {
        return;
      }
      if (other.Int != 0) {
        Int = other.Int;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Int = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class T : pb::IMessage<T> {
    private static readonly pb::MessageParser<T> _parser = new pb::MessageParser<T>(() => new T());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<T> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNet.Grpc.Test.Integration.Protoc.InheritenceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public T() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public T(T other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public T Clone() {
      return new T(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as T);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(T other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(T other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
