<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <RootNamespace>ProtoBuf.Grpc.Server</RootNamespace>
    <Title>protobuf-net.Grpc.AspNetCore</Title>
    <Description>Hosts code-first gRPC services in ASP.NET Core</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\protobuf-net.Grpc\protobuf-net.Grpc.csproj" />
    <PackageReference Include="Grpc.AspNetCore.Server" />
  </ItemGroup>
</Project>
