<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TargetFramework>$(DefaultTFM)</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="protobuf-net" VersionOverride="3.4.30" />
    <PackageReference Include="System.ServiceModel.Primitives" />

    <ProjectReference Condition="'$(ExampleRefs)'=='local'" Include="..\..\..\src\protobuf-net.Grpc\protobuf-net.Grpc.csproj" />
    <PackageReference Condition="'$(ExampleRefs)'=='nuget'" Include="protobuf-net.Grpc" />
    <!-- for security advisory (build warning -->
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

</Project>
