<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net472;netstandard2.1;netstandard2.0;net8.0;net10.0</TargetFrameworks>
        <RootNamespace>ProtoBuf.Grpc.Reflection</RootNamespace>
        <Title>protobuf-net.Grpc.Reflection</Title>
        <Description>Generates .proto schemas from code-first gRPC contracts, and implements the gRPC reflection service</Description>
    </PropertyGroup>

    <ItemGroup>
        <!-- note this uses v3 features that are not back-ported to v2 -->
        <PackageReference Include="protobuf-net.Reflection" />
        <PackageReference Include="protobuf-net" />
        <PackageReference Include="protobuf-net.Core" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\protobuf-net.Grpc\protobuf-net.Grpc.csproj" />
    </ItemGroup>

</Project>