using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ProtoBuf.Grpc.BuildTools;

internal static class ProxyEmitter
{
    public static string Emit(InterfaceModel iface)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0618 // ProtoBuf.Grpc.Internal.Reshape is intentionally obsoleted for direct consumption");
        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(iface.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(iface.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        // 1. partial interface declaration with [Proxy(typeof(...))]
        sb.Append("    [global::ProtoBuf.Grpc.Configuration.Proxy(typeof(global::").Append(iface.ProxyFullTypeName).AppendLine("))]");
        sb.Append("    ").Append(iface.InterfaceAccessibility).Append(" partial interface ").Append(iface.InterfaceName).AppendLine();
        sb.AppendLine("    {");
        sb.AppendLine("    }");
        sb.AppendLine();

        if (hasNamespace) sb.AppendLine("}");

        sb.AppendLine();
        sb.AppendLine("namespace ProtoBuf.Grpc.Generated");
        sb.AppendLine("{");

        sb.Append("    [global::System.CodeDom.Compiler.GeneratedCode(\"protobuf-net.Grpc.BuildTools\", \"1.0\")]").AppendLine();
        sb.Append("    [global::System.Diagnostics.DebuggerNonUserCode]").AppendLine();
        sb.Append("    internal sealed class ").Append(iface.ProxyTypeName).Append(" : global::Grpc.Core.ClientBase, ").Append(iface.InterfaceFullName).AppendLine();
        sb.AppendLine("    {");

        // ctor
        sb.Append("        public ").Append(iface.ProxyTypeName).AppendLine("(global::Grpc.Core.CallInvoker callInvoker) : base(callInvoker) { }");
        sb.AppendLine();

        // static factory (this is what ProxyEmitter.CreateViaActivator will pick up)
        sb.Append("        public static ").Append(iface.InterfaceFullName).Append(" Create(global::Grpc.Core.CallInvoker callInvoker)").AppendLine();
        sb.Append("            => new ").Append(iface.ProxyTypeName).Append("(callInvoker);").AppendLine();
        sb.AppendLine();

        // ToString override
        sb.Append("        public override string ToString() => \"").Append(iface.ServiceName.Replace("\"", "\\\"")).Append(" / CallInvoker\";").AppendLine();
        sb.AppendLine();

        // marshallers - dedupe by full type name
        var marshallerTypes = new SortedSet<string>(System.StringComparer.Ordinal);
        foreach (var op in iface.Operations)
        {
            marshallerTypes.Add(op.RequestTypeFullName);
            marshallerTypes.Add(op.ResponseTypeFullName);
        }

        var marshallerNames = new Dictionary<string, string>(System.StringComparer.Ordinal);
        int marshallerIndex = 0;
        foreach (var t in marshallerTypes)
        {
            var fieldName = "__m" + marshallerIndex++;
            marshallerNames[t] = fieldName;
            sb.Append("        private static readonly global::Grpc.Core.Marshaller<").Append(t).Append("> ").Append(fieldName).AppendLine();
            sb.Append("            = global::ProtoBuf.Grpc.Configuration.BinderConfiguration.Default.GetMarshaller<").Append(t).Append(">();").AppendLine();
        }
        sb.AppendLine();

        // Method<,> fields
        int opIndex = 0;
        var opFieldNames = new List<string>(iface.Operations.Length);
        foreach (var op in iface.Operations)
        {
            var fieldName = "__op" + opIndex++;
            opFieldNames.Add(fieldName);
            sb.Append("        private static readonly global::Grpc.Core.Method<").Append(op.RequestTypeFullName).Append(", ").Append(op.ResponseTypeFullName).Append("> ").Append(fieldName).AppendLine();
            sb.Append("            = new global::Grpc.Core.Method<").Append(op.RequestTypeFullName).Append(", ").Append(op.ResponseTypeFullName).Append(">(");
            sb.Append(MapMethodType(op.Kind)).Append(", ");
            sb.Append("\"").Append(EscapeString(iface.ServiceName)).Append("\", ");
            sb.Append("\"").Append(EscapeString(op.OperationName)).Append("\", ");
            sb.Append(marshallerNames[op.RequestTypeFullName]).Append(", ");
            sb.Append(marshallerNames[op.ResponseTypeFullName]).AppendLine(");");
        }
        sb.AppendLine();

        // operation implementations
        for (int i = 0; i < iface.Operations.Length; i++)
        {
            EmitOperation(sb, iface, iface.Operations[i], opFieldNames[i]);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitOperation(StringBuilder sb, InterfaceModel iface, OperationModel op, string opFieldName)
    {
        // explicit interface implementation
        sb.Append("        ").Append(op.ReturnTypeDisplay).Append(" ").Append(iface.InterfaceFullName).Append(".").Append(op.MethodName).Append("(");
        for (int i = 0; i < op.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(op.Parameters[i].TypeDisplay).Append(" ").Append(op.Parameters[i].Name);
        }
        sb.AppendLine(")");
        sb.AppendLine("        {");

        // resolve the call context
        switch (op.Context)
        {
            case ContextKind.None:
                // no local, pass `in CallContext.Default`
                break;
            case ContextKind.CallContext:
                // pass the user's `context` param directly (we'll use `in`)
                break;
            case ContextKind.CancellationToken:
                sb.Append("            global::ProtoBuf.Grpc.CallContext __ctx = ");
                sb.Append("(global::ProtoBuf.Grpc.CallContext)").Append(GetContextParameterName(op)).AppendLine(";");
                break;
        }

        // figure out reshape method name
        var reshapeMethod = GetReshapeMethodName(op);

        // request argument
        string requestExpr;
        switch (op.RequestShape)
        {
            case ArgShape.Data:
                requestExpr = op.Parameters[0].Name;
                break;
            case ArgShape.AsyncEnumerable:
                requestExpr = op.Parameters[0].Name;
                break;
            case ArgShape.Void:
            default:
                requestExpr = "global::ProtoBuf.Grpc.Internal.Empty.Instance";
                break;
        }

        // context expression
        string contextExpr = op.Context switch
        {
            ContextKind.CallContext => "in " + GetContextParameterName(op),
            ContextKind.CancellationToken => "in __ctx",
            _ => "in global::ProtoBuf.Grpc.CallContext.Default",
        };

        sb.Append("            ");
        if (!IsVoidLike(op)) sb.Append("return ");
        sb.Append("global::ProtoBuf.Grpc.Internal.Reshape.").Append(reshapeMethod).Append("(");
        sb.Append(contextExpr).Append(", ");
        sb.Append("this.CallInvoker, ").Append(opFieldName).Append(", ");
        sb.Append(requestExpr).Append(", null);");
        sb.AppendLine();

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string GetContextParameterName(OperationModel op)
    {
        // context is the second parameter when request is data/IAsyncEnumerable, else first
        if (op.RequestShape == ArgShape.Void)
        {
            return op.Parameters.Length > 0 ? op.Parameters[0].Name : "context";
        }
        return op.Parameters.Length > 1 ? op.Parameters[1].Name : "context";
    }

    private static bool IsVoidLike(OperationModel op)
    {
        // sync void or untyped Task/ValueTask
        if (op.ResponseShape == ResultShape.Sync && op.VoidResponse) return true;
        return false;
    }

    private static string MapMethodType(MethodKind kind) => kind switch
    {
        MethodKind.Unary => "global::Grpc.Core.MethodType.Unary",
        MethodKind.ServerStreaming => "global::Grpc.Core.MethodType.ServerStreaming",
        MethodKind.ClientStreaming => "global::Grpc.Core.MethodType.ClientStreaming",
        MethodKind.DuplexStreaming => "global::Grpc.Core.MethodType.DuplexStreaming",
        _ => "global::Grpc.Core.MethodType.Unary",
    };

    private static string GetReshapeMethodName(OperationModel op)
        => (op.Kind, op.ResponseShape, op.VoidResponse, op.RequestShape) switch
        {
            // unary
            (MethodKind.Unary, ResultShape.Task, false, _) => "UnaryTaskAsync",
            (MethodKind.Unary, ResultShape.Task, true, _) => "UnaryTaskAsync",
            (MethodKind.Unary, ResultShape.ValueTask, false, _) => "UnaryValueTaskAsync",
            (MethodKind.Unary, ResultShape.ValueTask, true, _) => "UnaryValueTaskAsyncVoid",
            (MethodKind.Unary, ResultShape.Sync, false, _) => "UnarySync",
            (MethodKind.Unary, ResultShape.Sync, true, _) => "UnarySyncVoid",

            // server-streaming
            (MethodKind.ServerStreaming, ResultShape.AsyncEnumerable, _, _) => "ServerStreamingAsync",

            // client-streaming (IAsyncEnumerable in, single response out)
            (MethodKind.ClientStreaming, ResultShape.Task, false, _) => "ClientStreamingTaskAsync",
            (MethodKind.ClientStreaming, ResultShape.Task, true, _) => "ClientStreamingTaskAsync",
            (MethodKind.ClientStreaming, ResultShape.ValueTask, false, _) => "ClientStreamingValueTaskAsync",
            (MethodKind.ClientStreaming, ResultShape.ValueTask, true, _) => "ClientStreamingValueTaskAsyncVoid",

            // duplex
            (MethodKind.DuplexStreaming, ResultShape.AsyncEnumerable, _, _) => "DuplexAsync",

            _ => "UnaryTaskAsync",
        };

    private static string EscapeString(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                default: sb.Append(ch); break;
            }
        }
        return sb.ToString();
    }
}

internal sealed record InterfaceModel(
    string Namespace,
    string InterfaceName,
    string InterfaceFullName,      // global::Ns.IFoo
    string InterfaceAccessibility, // public/internal
    string ServiceName,            // logical gRPC service name (Foo)
    string ProxyTypeName,          // unique class name to put in ProtoBuf.Grpc.Generated namespace
    string ProxyFullTypeName,      // ProtoBuf.Grpc.Generated.{ProxyTypeName}
    ImmutableArray<OperationModel> Operations);
