using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ProtoBuf.Grpc.BuildTools;

internal static class ProxyEmitter
{
    public static string Emit(InterfaceModel iface)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0618 // ProtoBuf.Grpc.Internal.Reshape is intentionally obsoleted for direct consumption");
        sb.AppendLine();

        sb.AppendLine("namespace ProtoBuf.Grpc.Generated");
        sb.AppendLine("{");

        EmitClientProxy(sb, iface);
        sb.AppendLine();
        EmitServerBindings(sb, iface);
        sb.AppendLine();
        EmitModuleInitializer(sb, iface);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitModuleInitializer(StringBuilder sb, InterfaceModel iface)
    {
        // A per-interface [ModuleInitializer] populates the GeneratedProxyRegistry. The trimmer/AOT
        // compiler can see this as a static reference graph; no runtime attribute lookup needed.
        sb.Append("    [global::System.CodeDom.Compiler.GeneratedCode(\"protobuf-net.Grpc.BuildTools\", \"1.0\")]").AppendLine();
        sb.Append("    internal static class ").Append(iface.InitTypeName).AppendLine();
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Init()");
        sb.AppendLine("        {");
        sb.Append("            global::ProtoBuf.Grpc.Internal.GeneratedProxyRegistry.RegisterClient<").Append(iface.InterfaceFullName).Append(">(").Append(iface.ProxyTypeName).Append(".Create);").AppendLine();
        sb.Append("            global::ProtoBuf.Grpc.Internal.GeneratedProxyRegistry.RegisterServer(typeof(").Append(iface.InterfaceFullName).Append("), typeof(").Append(iface.ServerBindingsTypeName).Append("));").AppendLine();
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void EmitClientProxy(StringBuilder sb, InterfaceModel iface)
    {
        sb.Append("    [global::System.CodeDom.Compiler.GeneratedCode(\"protobuf-net.Grpc.BuildTools\", \"1.0\")]").AppendLine();
        sb.Append("    [global::System.Diagnostics.DebuggerNonUserCode]").AppendLine();
        sb.Append("    internal sealed class ").Append(iface.ProxyTypeName).Append(" : global::Grpc.Core.ClientBase, ").Append(iface.InterfaceFullName).AppendLine();
        sb.AppendLine("    {");

        // marshallers + Method<,> are instance readonly fields so they can be built from the caller-
        // supplied BinderConfiguration (which may register custom marshaller factories — the static
        // BinderConfiguration.Default doesn't see those, so a static-field cache would crash any service
        // whose payload type isn't marshallable under the defaults).

        // dedupe marshallers by full type name
        var marshallerTypes = new SortedSet<string>(System.StringComparer.Ordinal);
        foreach (var op in iface.Operations)
        {
            marshallerTypes.Add(op.RequestTypeFullName);
            marshallerTypes.Add(op.ResponseTypeFullName);
        }

        var marshallerNames = new Dictionary<string, string>(System.StringComparer.Ordinal);
        int marshallerIndex = 0;
        foreach (var t in marshallerTypes)
        {
            var fieldName = "__m" + marshallerIndex++;
            marshallerNames[t] = fieldName;
            sb.Append("        private readonly global::Grpc.Core.Marshaller<").Append(t).Append("> ").Append(fieldName).AppendLine(";");
        }

        var opFieldNames = new List<string>(iface.Operations.Length);
        for (int i = 0; i < iface.Operations.Length; i++)
        {
            var op = iface.Operations[i];
            var fieldName = "__op" + i;
            opFieldNames.Add(fieldName);
            sb.Append("        private readonly global::Grpc.Core.Method<").Append(op.RequestTypeFullName).Append(", ").Append(op.ResponseTypeFullName).Append("> ").Append(fieldName).AppendLine(";");
        }
        sb.AppendLine();

        // ctor(CallInvoker, BinderConfiguration) — the registry calls this
        sb.Append("        public ").Append(iface.ProxyTypeName).Append("(global::Grpc.Core.CallInvoker callInvoker, global::ProtoBuf.Grpc.Configuration.BinderConfiguration config) : base(callInvoker)").AppendLine();
        sb.AppendLine("        {");
        sb.AppendLine("            if (config is null) config = global::ProtoBuf.Grpc.Configuration.BinderConfiguration.Default;");
        foreach (var t in marshallerTypes)
        {
            sb.Append("            ").Append(marshallerNames[t]).Append(" = config.GetMarshaller<").Append(t).AppendLine(">();");
        }
        for (int i = 0; i < iface.Operations.Length; i++)
        {
            var op = iface.Operations[i];
            sb.Append("            ").Append(opFieldNames[i]).Append(" = new global::Grpc.Core.Method<").Append(op.RequestTypeFullName).Append(", ").Append(op.ResponseTypeFullName).Append(">(");
            sb.Append(MapMethodType(op.Kind)).Append(", ");
            sb.Append("\"").Append(EscapeString(iface.ServiceName)).Append("\", ");
            sb.Append("\"").Append(EscapeString(op.OperationName)).Append("\", ");
            sb.Append(marshallerNames[op.RequestTypeFullName]).Append(", ");
            sb.Append(marshallerNames[op.ResponseTypeFullName]).AppendLine(");");
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        // back-compat ctor(CallInvoker) — used by manual [Proxy(typeof(X))] consumers
        sb.Append("        public ").Append(iface.ProxyTypeName).Append("(global::Grpc.Core.CallInvoker callInvoker)").AppendLine();
        sb.Append("            : this(callInvoker, global::ProtoBuf.Grpc.Configuration.BinderConfiguration.Default) { }").AppendLine();
        sb.AppendLine();

        // static factories: Create(CallInvoker, BinderConfiguration) for the registry path,
        // Create(CallInvoker) for the [Proxy(typeof(X))] path.
        sb.Append("        public static ").Append(iface.InterfaceFullName).Append(" Create(global::Grpc.Core.CallInvoker callInvoker, global::ProtoBuf.Grpc.Configuration.BinderConfiguration config)").AppendLine();
        sb.Append("            => new ").Append(iface.ProxyTypeName).Append("(callInvoker, config);").AppendLine();
        sb.AppendLine();
        sb.Append("        public static ").Append(iface.InterfaceFullName).Append(" Create(global::Grpc.Core.CallInvoker callInvoker)").AppendLine();
        sb.Append("            => new ").Append(iface.ProxyTypeName).Append("(callInvoker);").AppendLine();
        sb.AppendLine();

        // ToString override
        sb.Append("        public override string ToString() => \"").Append(iface.ServiceName.Replace("\"", "\\\"")).Append(" / CallInvoker\";").AppendLine();
        sb.AppendLine();

        // operation implementations
        for (int i = 0; i < iface.Operations.Length; i++)
        {
            EmitClientOperation(sb, iface, iface.Operations[i], opFieldNames[i]);
        }

        sb.AppendLine("    }");
    }

    private static void EmitClientOperation(StringBuilder sb, InterfaceModel iface, OperationModel op, string opFieldName)
    {
        // explicit interface implementation
        sb.Append("        ").Append(op.ReturnTypeDisplay).Append(" ").Append(iface.InterfaceFullName).Append(".").Append(op.MethodName).Append("(");
        for (int i = 0; i < op.Parameters.Length; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(op.Parameters[i].TypeDisplay).Append(" ").Append(op.Parameters[i].Name);
        }
        sb.AppendLine(")");
        sb.AppendLine("        {");

        // resolve the call context
        switch (op.Context)
        {
            case ContextKind.None:
            case ContextKind.CallContext:
                break;
            case ContextKind.CancellationToken:
                sb.Append("            global::ProtoBuf.Grpc.CallContext __ctx = ");
                sb.Append("(global::ProtoBuf.Grpc.CallContext)").Append(GetContextParameterName(op)).AppendLine(";");
                break;
        }

        var reshapeMethod = GetClientReshapeMethodName(op);

        string requestExpr = op.RequestShape switch
        {
            ArgShape.Data => op.Parameters[0].Name,
            ArgShape.AsyncEnumerable => op.Parameters[0].Name,
            _ => "global::ProtoBuf.Grpc.Internal.Empty.Instance",
        };

        string contextExpr = op.Context switch
        {
            ContextKind.CallContext => "in " + GetContextParameterName(op),
            ContextKind.CancellationToken => "in __ctx",
            _ => "in global::ProtoBuf.Grpc.CallContext.Default",
        };

        sb.Append("            ");
        if (!IsVoidLikeClientReturn(op)) sb.Append("return ");
        sb.Append("global::ProtoBuf.Grpc.Internal.Reshape.").Append(reshapeMethod).Append("(");
        sb.Append(contextExpr).Append(", ");
        sb.Append("this.CallInvoker, ").Append(opFieldName).Append(", ");
        sb.Append(requestExpr).Append(", null);");
        sb.AppendLine();

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // -------- server bindings --------

    private static void EmitServerBindings(StringBuilder sb, InterfaceModel iface)
    {
        sb.Append("    [global::System.CodeDom.Compiler.GeneratedCode(\"protobuf-net.Grpc.BuildTools\", \"1.0\")]").AppendLine();
        sb.Append("    [global::System.Diagnostics.DebuggerNonUserCode]").AppendLine();
        sb.Append("    public static class ").Append(iface.ServerBindingsTypeName).AppendLine();
        sb.AppendLine("    {");

        // marshallers + Method<,> fields shared with the client proxy live there too, but since the
        // client proxy lives in the same compilation we *could* reuse them. simpler: declare our own.
        var marshallerTypes = new SortedSet<string>(System.StringComparer.Ordinal);
        foreach (var op in iface.Operations)
        {
            marshallerTypes.Add(op.RequestTypeFullName);
            marshallerTypes.Add(op.ResponseTypeFullName);
        }

        // No static marshaller / Method<,> fields. Marshallers come from the caller-supplied
        // BinderConfiguration (custom marshaller factories live there); resolving them eagerly in the
        // cctor would crash the whole class for services whose payloads aren't marshallable under the
        // defaults. Build everything as locals inside Bind<TService> using binder.Configuration.

        // public static int Bind<TService>(IServerMethodBinder<TService> binder)
        sb.Append("        public static int Bind<TService>(global::ProtoBuf.Grpc.Configuration.IServerMethodBinder<TService> binder)").AppendLine();
        sb.Append("            where TService : class, ").Append(iface.InterfaceFullName).AppendLine();
        sb.AppendLine("        {");
        sb.AppendLine("            var __cfg = binder.Configuration;");
        sb.AppendLine("            int count = 0;");

        for (int i = 0; i < iface.Operations.Length; i++)
        {
            var op = iface.Operations[i];
            var ifaceFq = iface.InterfaceFullName;
            var opNameLiteral = "\"" + EscapeString(op.MethodName) + "\"";

            // Each operation is bound inside its own try/catch — mirrors the IL emitter's
            // per-method tolerance so one bad type (no marshaller, etc.) doesn't take down the
            // whole interface bind.
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.Append("                var __m_req = __cfg.GetMarshaller<").Append(op.RequestTypeFullName).AppendLine(">();");
            if (!string.Equals(op.RequestTypeFullName, op.ResponseTypeFullName, System.StringComparison.Ordinal))
            {
                sb.Append("                var __m_resp = __cfg.GetMarshaller<").Append(op.ResponseTypeFullName).AppendLine(">();");
            }
            var respMarshaller = string.Equals(op.RequestTypeFullName, op.ResponseTypeFullName, System.StringComparison.Ordinal) ? "__m_req" : "__m_resp";
            sb.Append("                var __op = new global::Grpc.Core.Method<").Append(op.RequestTypeFullName).Append(", ").Append(op.ResponseTypeFullName).Append(">(");
            sb.Append(MapMethodType(op.Kind)).Append(", ");
            sb.Append("\"").Append(EscapeString(iface.ServiceName)).Append("\", ");
            sb.Append("\"").Append(EscapeString(op.OperationName)).Append("\", ");
            sb.Append("__m_req, ").Append(respMarshaller).AppendLine(");");

            switch (op.Kind)
            {
                case MethodKind.Unary:
                    sb.Append("                binder.AddUnaryMethod<").Append(op.RequestTypeFullName).Append(", ").Append(op.ResponseTypeFullName).Append(">(")
                      .Append("__op, binder.GetMetadata(typeof(").Append(ifaceFq).Append("), ").Append(opNameLiteral).Append("), ")
                      .Append(GetServerHandlerName(op)).Append("<TService>);").AppendLine();
                    break;
                case MethodKind.ServerStreaming:
                    sb.Append("                binder.AddServerStreamingMethod<").Append(op.RequestTypeFullName).Append(", ").Append(op.ResponseTypeFullName).Append(">(")
                      .Append("__op, binder.GetMetadata(typeof(").Append(ifaceFq).Append("), ").Append(opNameLiteral).Append("), ")
                      .Append(GetServerHandlerName(op)).Append("<TService>);").AppendLine();
                    break;
                case MethodKind.ClientStreaming:
                    sb.Append("                binder.AddClientStreamingMethod<").Append(op.RequestTypeFullName).Append(", ").Append(op.ResponseTypeFullName).Append(">(")
                      .Append("__op, binder.GetMetadata(typeof(").Append(ifaceFq).Append("), ").Append(opNameLiteral).Append("), ")
                      .Append(GetServerHandlerName(op)).Append("<TService>);").AppendLine();
                    break;
                case MethodKind.DuplexStreaming:
                    sb.Append("                binder.AddDuplexStreamingMethod<").Append(op.RequestTypeFullName).Append(", ").Append(op.ResponseTypeFullName).Append(">(")
                      .Append("__op, binder.GetMetadata(typeof(").Append(ifaceFq).Append("), ").Append(opNameLiteral).Append("), ")
                      .Append(GetServerHandlerName(op)).Append("<TService>);").AppendLine();
                    break;
            }
            sb.AppendLine("                count++;");
            sb.AppendLine("            }");
            sb.Append("            catch (global::System.Exception __ex) { binder.OnBindFailed(").Append(opNameLiteral).AppendLine(", __ex); }");
        }

        sb.AppendLine("            return count;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // per-op generic static handler methods
        foreach (var op in iface.Operations)
        {
            EmitServerOperationHandler(sb, iface, op);
        }

        sb.AppendLine("    }");
    }

    private static string GetServerHandlerName(OperationModel op) => op.MethodName + "_Server_" + op.Kind;

    private static void EmitServerOperationHandler(StringBuilder sb, InterfaceModel iface, OperationModel op)
    {
        var ifaceFq = iface.InterfaceFullName;
        var serverContext = "global::Grpc.Core.ServerCallContext";
        var name = GetServerHandlerName(op);

        switch (op.Kind)
        {
            case MethodKind.Unary:
                // signature: Task<TResponse>(TService, TRequest, ServerCallContext)
                sb.Append("        private static global::System.Threading.Tasks.Task<").Append(op.ResponseTypeFullName)
                  .Append("> ").Append(name).Append("<TService>(TService service, ").Append(op.RequestTypeFullName)
                  .Append(" request, ").Append(serverContext).Append(" ctx)").AppendLine();
                sb.Append("            where TService : class, ").Append(ifaceFq).AppendLine();
                sb.AppendLine("        {");
                EmitUnaryBody(sb, op);
                sb.AppendLine("        }");
                break;

            case MethodKind.ServerStreaming:
                // signature: Task(TService, TRequest, IServerStreamWriter<TResponse>, ServerCallContext)
                sb.Append("        private static global::System.Threading.Tasks.Task ").Append(name)
                  .Append("<TService>(TService service, ").Append(op.RequestTypeFullName)
                  .Append(" request, global::Grpc.Core.IServerStreamWriter<").Append(op.ResponseTypeFullName)
                  .Append("> writer, ").Append(serverContext).Append(" ctx)").AppendLine();
                sb.Append("            where TService : class, ").Append(ifaceFq).AppendLine();
                sb.AppendLine("        {");
                EmitServerStreamingBody(sb, op);
                sb.AppendLine("        }");
                break;

            case MethodKind.ClientStreaming:
                // signature: Task<TResponse>(TService, IAsyncStreamReader<TRequest>, ServerCallContext)
                sb.Append("        private static global::System.Threading.Tasks.Task<").Append(op.ResponseTypeFullName)
                  .Append("> ").Append(name).Append("<TService>(TService service, global::Grpc.Core.IAsyncStreamReader<")
                  .Append(op.RequestTypeFullName).Append("> reader, ").Append(serverContext).Append(" ctx)").AppendLine();
                sb.Append("            where TService : class, ").Append(ifaceFq).AppendLine();
                sb.AppendLine("        {");
                EmitClientStreamingBody(sb, op);
                sb.AppendLine("        }");
                break;

            case MethodKind.DuplexStreaming:
                // signature: Task(TService, IAsyncStreamReader<TRequest>, IServerStreamWriter<TResponse>, ServerCallContext)
                sb.Append("        private static global::System.Threading.Tasks.Task ").Append(name)
                  .Append("<TService>(TService service, global::Grpc.Core.IAsyncStreamReader<").Append(op.RequestTypeFullName)
                  .Append("> reader, global::Grpc.Core.IServerStreamWriter<").Append(op.ResponseTypeFullName)
                  .Append("> writer, ").Append(serverContext).Append(" ctx)").AppendLine();
                sb.Append("            where TService : class, ").Append(ifaceFq).AppendLine();
                sb.AppendLine("        {");
                EmitDuplexStreamingBody(sb, op);
                sb.AppendLine("        }");
                break;
        }
        sb.AppendLine();
    }

    private static void EmitContextLocalIfNeeded(StringBuilder sb, OperationModel op)
    {
        switch (op.Context)
        {
            case ContextKind.CallContext:
                sb.AppendLine("            var __cc = new global::ProtoBuf.Grpc.CallContext(service, ctx);");
                break;
            case ContextKind.CancellationToken:
                sb.AppendLine("            var __ct = ctx.CancellationToken;");
                break;
        }
    }

    private static string ServiceCallArgs(OperationModel op, string requestExpr)
    {
        // build the (args) string for service.Method(...)
        var parts = new List<string>(2);
        if (!op.VoidRequest) parts.Add(requestExpr);
        switch (op.Context)
        {
            case ContextKind.CallContext: parts.Add("__cc"); break;
            case ContextKind.CancellationToken: parts.Add("__ct"); break;
        }
        return string.Join(", ", parts);
    }

    private static void EmitUnaryBody(StringBuilder sb, OperationModel op)
    {
        EmitContextLocalIfNeeded(sb, op);
        var callArgs = ServiceCallArgs(op, "request");
        var call = "service." + op.MethodName + "(" + callArgs + ")";

        switch (op.ResponseShape)
        {
            case ResultShape.Task:
                if (op.VoidResponse)
                {
                    // service returns Task; convert to Task<Empty>
                    sb.Append("            return global::ProtoBuf.Grpc.Internal.Reshape.EmptyTask(").Append(call).AppendLine(");");
                }
                else
                {
                    sb.Append("            return ").Append(call).AppendLine(";");
                }
                break;
            case ResultShape.ValueTask:
                if (op.VoidResponse)
                {
                    sb.Append("            return global::ProtoBuf.Grpc.Internal.Reshape.EmptyValueTask(").Append(call).AppendLine(");");
                }
                else
                {
                    sb.Append("            return ").Append(call).AppendLine(".AsTask();");
                }
                break;
            case ResultShape.Sync:
                if (op.VoidResponse)
                {
                    sb.Append("            ").Append(call).AppendLine(";");
                    sb.AppendLine("            return global::ProtoBuf.Grpc.Internal.Empty.InstanceTask;");
                }
                else
                {
                    sb.Append("            return global::System.Threading.Tasks.Task.FromResult(").Append(call).AppendLine(");");
                }
                break;
            default:
                sb.AppendLine("            throw new global::System.NotSupportedException(\"Unsupported response shape\");");
                break;
        }
    }

    private static void EmitServerStreamingBody(StringBuilder sb, OperationModel op)
    {
        EmitContextLocalIfNeeded(sb, op);
        var callArgs = ServiceCallArgs(op, "request");
        var call = "service." + op.MethodName + "(" + callArgs + ")";
        // service returns IAsyncEnumerable<TResponse>; reshape into the writer
        sb.Append("            return global::ProtoBuf.Grpc.Internal.Reshape.WriteTo<").Append(op.ResponseTypeFullName).Append(">(").Append(call).AppendLine(", writer, ctx.CancellationToken);");
    }

    private static void EmitClientStreamingBody(StringBuilder sb, OperationModel op)
    {
        EmitContextLocalIfNeeded(sb, op);
        // reader -> IAsyncEnumerable<TRequest>
        sb.Append("            var seq = global::ProtoBuf.Grpc.Internal.Reshape.AsAsyncEnumerable<").Append(op.RequestTypeFullName).AppendLine(">(reader, ctx.CancellationToken);");
        var callArgs = ServiceCallArgs(op, "seq");
        var call = "service." + op.MethodName + "(" + callArgs + ")";

        switch (op.ResponseShape)
        {
            case ResultShape.Task:
                if (op.VoidResponse)
                {
                    sb.Append("            return global::ProtoBuf.Grpc.Internal.Reshape.EmptyTask(").Append(call).AppendLine(");");
                }
                else
                {
                    sb.Append("            return ").Append(call).AppendLine(";");
                }
                break;
            case ResultShape.ValueTask:
                if (op.VoidResponse)
                {
                    sb.Append("            return global::ProtoBuf.Grpc.Internal.Reshape.EmptyValueTask(").Append(call).AppendLine(");");
                }
                else
                {
                    sb.Append("            return ").Append(call).AppendLine(".AsTask();");
                }
                break;
            case ResultShape.Sync:
                if (op.VoidResponse)
                {
                    sb.Append("            ").Append(call).AppendLine(";");
                    sb.AppendLine("            return global::ProtoBuf.Grpc.Internal.Empty.InstanceTask;");
                }
                else
                {
                    sb.Append("            return global::System.Threading.Tasks.Task.FromResult(").Append(call).AppendLine(");");
                }
                break;
            default:
                sb.AppendLine("            throw new global::System.NotSupportedException(\"Unsupported response shape\");");
                break;
        }
    }

    private static void EmitDuplexStreamingBody(StringBuilder sb, OperationModel op)
    {
        EmitContextLocalIfNeeded(sb, op);
        sb.Append("            var seq = global::ProtoBuf.Grpc.Internal.Reshape.AsAsyncEnumerable<").Append(op.RequestTypeFullName).AppendLine(">(reader, ctx.CancellationToken);");
        var callArgs = ServiceCallArgs(op, "seq");
        var call = "service." + op.MethodName + "(" + callArgs + ")";
        sb.Append("            return global::ProtoBuf.Grpc.Internal.Reshape.WriteTo<").Append(op.ResponseTypeFullName).Append(">(").Append(call).AppendLine(", writer, ctx.CancellationToken);");
    }

    // -------- shared helpers --------

    private static string GetContextParameterName(OperationModel op)
    {
        if (op.RequestShape == ArgShape.Void)
        {
            return op.Parameters.Length > 0 ? op.Parameters[0].Name : "context";
        }
        return op.Parameters.Length > 1 ? op.Parameters[1].Name : "context";
    }

    private static bool IsVoidLikeClientReturn(OperationModel op)
        => op.ResponseShape == ResultShape.Sync && op.VoidResponse;

    private static string MapMethodType(MethodKind kind) => kind switch
    {
        MethodKind.Unary => "global::Grpc.Core.MethodType.Unary",
        MethodKind.ServerStreaming => "global::Grpc.Core.MethodType.ServerStreaming",
        MethodKind.ClientStreaming => "global::Grpc.Core.MethodType.ClientStreaming",
        MethodKind.DuplexStreaming => "global::Grpc.Core.MethodType.DuplexStreaming",
        _ => "global::Grpc.Core.MethodType.Unary",
    };

    private static string GetClientReshapeMethodName(OperationModel op)
        => (op.Kind, op.ResponseShape, op.VoidResponse, op.RequestShape) switch
        {
            (MethodKind.Unary, ResultShape.Task, false, _) => "UnaryTaskAsync",
            (MethodKind.Unary, ResultShape.Task, true, _) => "UnaryTaskAsync",
            (MethodKind.Unary, ResultShape.ValueTask, false, _) => "UnaryValueTaskAsync",
            (MethodKind.Unary, ResultShape.ValueTask, true, _) => "UnaryValueTaskAsyncVoid",
            (MethodKind.Unary, ResultShape.Sync, false, _) => "UnarySync",
            (MethodKind.Unary, ResultShape.Sync, true, _) => "UnarySyncVoid",
            (MethodKind.ServerStreaming, ResultShape.AsyncEnumerable, _, _) => "ServerStreamingAsync",
            (MethodKind.ClientStreaming, ResultShape.Task, false, _) => "ClientStreamingTaskAsync",
            (MethodKind.ClientStreaming, ResultShape.Task, true, _) => "ClientStreamingTaskAsync",
            (MethodKind.ClientStreaming, ResultShape.ValueTask, false, _) => "ClientStreamingValueTaskAsync",
            (MethodKind.ClientStreaming, ResultShape.ValueTask, true, _) => "ClientStreamingValueTaskAsyncVoid",
            (MethodKind.DuplexStreaming, ResultShape.AsyncEnumerable, _, _) => "DuplexAsync",
            _ => "UnaryTaskAsync",
        };

    private static string EscapeString(string value)
    {
        if (string.IsNullOrEmpty(value)) return value;
        var sb = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                default: sb.Append(ch); break;
            }
        }
        return sb.ToString();
    }
}

internal sealed record InterfaceModel(
    string Namespace,
    string InterfaceName,
    string InterfaceFullName,          // global::Ns.IFoo
    string ServiceName,                // logical gRPC service name (Foo)
    string ProxyTypeName,              // generated client class name in ProtoBuf.Grpc.Generated namespace
    string ProxyFullTypeName,          // ProtoBuf.Grpc.Generated.{ProxyTypeName}
    string ServerBindingsTypeName,     // generated server-bindings class name in ProtoBuf.Grpc.Generated namespace
    string ServerBindingsFullTypeName, // ProtoBuf.Grpc.Generated.{ServerBindingsTypeName}
    string InitTypeName,               // generated module-init class name in ProtoBuf.Grpc.Generated namespace
    ImmutableArray<OperationModel> Operations);
