using System;

namespace ProtoBuf.Grpc.Configuration
{
    /// <summary>
    /// Indicates that a proxy should be automatically generated by build tooling, if available
    /// </summary>
    [AttributeUsage(AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    public sealed class GenerateProxyAttribute : Attribute { }
}
