using System;
using ProtoBuf.Grpc.Internal;
using System.Diagnostics.CodeAnalysis;

namespace ProtoBuf.Grpc.Configuration
{
    /// <summary>
    /// Marks a partial class deriving from <see cref="ClientFactory"/> as the compile-time home for
    /// gRPC client proxies and server bindings, generated by protobuf-net.BuildTools.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The generator fills in the other half of the class: a <see cref="ClientFactory.CreateClient{TService}"/>
    /// override that dispatches by <c>typeof</c>, one client proxy per contract, and - where an
    /// implementation is named and Grpc.AspNetCore.Server is referenced - one
    /// <c>IServiceMethodProvider&lt;TImpl&gt;</c> per implementation plus a registration extension.
    /// </para>
    /// <para>
    /// Nothing is registered or discovered at run time, which is what makes the result survive
    /// trimming and native AOT. Set <see cref="Model"/> to a <c>[ProtoModel]</c> type, or the
    /// payloads are still marshalled through <c>RuntimeTypeModel.Default</c>, which reflects - the
    /// proxies would be AOT-safe and the bytes they carry would not.
    /// </para>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    [Experimental(Experiments.BuildTimeProxies, UrlFormat = Experiments.BuildTimeProxiesUrlFormat)]
    public sealed class ProtoGrpcAttribute : Attribute
    {
        /// <summary>
        /// The <c>[ProtoModel]</c>-generated <see cref="ProtoBuf.Meta.TypeModel"/> to marshal
        /// payloads through.
        /// </summary>
        public Type? Model { get; set; }

        /// <summary>
        /// The name of the generated <c>IServiceCollection</c> extension method; defaults to
        /// <c>Add</c> followed by the declaring type's name.
        /// </summary>
        public string? RegistrationMethodName { get; set; }
    }

    /// <summary>
    /// Names a service contract for a <see cref="ProtoGrpcAttribute"/> type to generate, and
    /// optionally the implementation to bind on the server. Repeat for each contract.
    /// </summary>
    /// <remarks>
    /// The contract is resolved from metadata, so it may live in a referenced assembly - which is
    /// the common shape, since service contracts usually ship in a shared package.
    /// </remarks>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
    [Experimental(Experiments.BuildTimeProxies, UrlFormat = Experiments.BuildTimeProxiesUrlFormat)]
    public sealed class ProtoServiceAttribute : Attribute
    {
        /// <summary>
        /// Generate a client proxy for <paramref name="contract"/>. No server bindings are generated:
        /// use the two-argument form in the project that hosts the service.
        /// </summary>
        public ProtoServiceAttribute(Type contract) => Contract = contract;

        /// <summary>
        /// Generate a client proxy for <paramref name="contract"/>, and server bindings for
        /// <paramref name="implementation"/>.
        /// </summary>
        public ProtoServiceAttribute(Type contract, Type implementation)
        {
            Contract = contract;
            Implementation = implementation;
        }

        /// <summary>The service contract interface.</summary>
        public Type Contract { get; }

        /// <summary>
        /// The implementation to bind on the server, if this project hosts the service.
        /// </summary>
        /// <remarks>
        /// Naming it is what lets the generated server bindings close their generics at compile
        /// time: <c>IServiceMethodProvider&lt;TService&gt;</c> is generic in the implementation, so
        /// without one there is nothing to instantiate it with and the binding would have to go
        /// through <c>MakeGenericMethod</c>.
        /// </remarks>
        public Type? Implementation { get; }
    }
}
