<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
    <RootNamespace>ProtoBuf.Grpc.ClientFactory</RootNamespace>
    <Title>protobuf-net.Grpc.ClientFactory</Title>
    <Description>Code-first gRPC clients for dependency injection, via HttpClientFactory</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <ProjectReference Include="..\protobuf-net.Grpc\protobuf-net.Grpc.csproj" />
  </ItemGroup>

</Project>
